# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# mod properties
maven_group=work.lclpnet.mods
mod_id=simple-ac
mod_version=0.1.0

# Minecraft version compatibility until the next minor version (major.minor.patch = major.minor.>=patch)
minecraft_compat=1.21.11