[versions]
minecraft = "1.21.11"
fabric-api = "0.141.3+1.21.11"
fabric-loader = "0.18.4"
fabric-loom = "1.15-SNAPSHOT"
gradle-build-tools = "1.7.0"
java = "21"
kotlin = "2.3.10"
fabric-language-kotlin = "1.13.9+kotlin.2.3.10"
kibu = "0.153.3+1.21.11"

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
gradle-build-tools = { id = "gradle-build-utils", version.ref = "gradle-build-tools" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kibu = { module = "work.lclpnet.mods.kibu:kibu", version.ref="kibu" }